name: Auto Build and Release EXE

on:
  push:
    branches:
      - main  # 或你用的分支名

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE from wmscq.py
      run: |
        pyinstaller --onefile --noupx --name wmscq wmscq.py

    - name: Generate timestamp version tag
      id: generate_tag
      run: |
        echo "TAG_NAME=v0.1.$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

    - name: Create Git Tag
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: Release ${{ env.TAG_NAME }}
        files: dist/wmscq.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
